# Loop feature will be removed in version 2.11
=================Approach1================================================
---
- hosts: localhost
  become: true
  tasks:
   - name: Install list of packages
     yum:
      name: ['httpd', 'wget', 'vim', 'zip', 'unzip']
...
===================Approach2==============================================
---
- hosts: localhost
  become: true
  tasks:
    - name: Install list of packages
      yum:
        name:
          - httpd
          - wget
          - vim
          - zip
          - unzip
        state: present
